(async()=>{
const raw=await PortfolioStore.read();
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeValue=v=>Array.isArray(v)?v.map(safeValue):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,safeValue(x)])):typeof v==='string'?escapeText(v):v;
const safe=o=>safeValue(o);
const projects=raw.projects.filter(p=>p.published).map(safe),memos=raw.memos.filter(m=>m.published).map(safe),profile=safe(raw.profile);
const lines=s=>s.replace(/\n/g,'<br>');
const main=document.querySelector('main');let filter='all',projectPage=1;let proto={};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function art(p){if(p.cover)return `<div class="art"><img class="uploaded-cover" src="${p.cover}" alt="${p.name}"></div>`;const black=p.id==='folio'||p.id==='afterimage';return `<div class="art ${black?'black':''}"><span class="backtype">${p.art==='phone'?p.name:''}</span>${p.art==='phone'?`<div class="phone"><div class="notch"></div><small>${p.name.toUpperCase()} / YOUR EVERYDAY</small><h3>${p.id==='onul'?'오늘은,<br>어떤 하루인가요?':p.id==='folio'?'A shelf<br>of your own.':'어디로<br>가볼까요?'}</h3><div class="circle">${p.id==='onul'?'✳':p.id==='folio'?'f.':'↗'}</div><div class="line">${p.id==='onul'?'오늘의 작은 기록':p.id==='folio'?'Your reading collection':'나의 동네, 새로운 발견'}</div><div class="line">${p.id==='onul'?'나를 돌보는 시간':p.id==='folio'?'Recently added':'이번 주의 장소'}</div></div>`:p.art==='poster'?`<div class="poster" style="color:#111"><small>PERSONAL EXPLORATION — ${p.year}</small><strong>${p.id==='between'?'Between<br>the lines.':'After<br>image.'}</strong><img src="assets/${p.gif}.gif" alt="흑백 기하학 움직임"><small>STUDIES IN FORM & EVERYDAY LIFE</small></div>`:`<div class="orbital">${[0,30,60,90,120,150].map(r=>`<i style="--r:${r}deg"></i>`).join('')}</div>`}<span class="art-caption">${p.type.toUpperCase()}</span></div>`}
function card(p){return `<a class="card" href="#projects/${p.id}" aria-label="${p.name} 프로젝트 보기"><span class="card-flip"><span class="card-face card-front">${art({...p,cover:p.thumbnail||p.cover})}</span><span class="card-face card-back"><small>${p.category==='uxui'?'UXUI':'ILLUST'} · ${p.year}</small><span><strong>${p.name}</strong><em>${p.tag}</em></span><b aria-hidden="true">↗</b></span></span></a>`}
function home(){const uxPositions=[[50,23],[57,40],[35,53],[67,30],[43,68],[72,61],[28,38],[55,78]],illPositions=[[49,60],[72,48],[38,70],[62,76],[27,60],[76,67],[45,82],[60,56]];let uxIndex=0,illIndex=0;return `<section class="archive-home" aria-labelledby="archive-title">
  <div class="identity-panel">
    <p class="archive-role">Product Design * Illust<br>portfolio Archive</p>
    <h1 class="name-image-wrap" id="archive-title"><span>權我炫</span></h1>
    <p class="home-bio">${lines(profile.intro)}</p>
    <div class="social-links" aria-label="연락처">
      <a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 32 32" aria-hidden="true"><rect x="3" y="3" width="26" height="26" rx="7"/><circle cx="16" cy="16" r="6"/><circle class="fill" cx="24" cy="8" r="1.7"/></svg></a>
      <a href="#contact" aria-label="Contact"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M8.2 4.5 4.7 7.1c-1.8 1.3.8 8.1 6.4 13.7s12.4 8.2 13.7 6.4l2.7-3.5c.7-1 .4-2.3-.6-2.9l-5.1-3c-.9-.5-2-.3-2.6.5l-1.7 2.1c-2.5-1.3-4.7-3.5-6-6l2.1-1.7c.8-.7 1-1.8.5-2.7l-3-5.1c-.6-1-1.9-1.2-2.9-.4Z"/></svg></a>
      <a href="mailto:${profile.email}" aria-label="Email"><svg viewBox="0 0 36 30" aria-hidden="true"><rect x="2" y="3" width="32" height="24" rx="1"/><path d="m3 5 15 11L33 5"/></svg></a>
    </div>
    <button class="sound-toggle" type="button" aria-pressed="false" aria-label="배경 음악 재생"><span class="player-play" aria-hidden="true">▶</span><span class="sound-line" aria-hidden="true"><i></i></span></button>
    <iframe id="archive-audio" class="audio-frame" width="400" height="25" src="https://www.youtube.com/embed/Fwv2gnCFDOc?si=yEx8ZZZTXJRnSRaM&amp;controls=0&amp;enablejsapi=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
  </div>
  <div class="work-orbit" aria-label="작업물 바로가기">
    <canvas class="lotus-canvas" id="lotus-canvas" aria-hidden="true"></canvas>
    <a class="orbit-label label-uxui" href="#projects" data-home-filter="uxui">UXUI</a>
    <a class="orbit-label label-illust" href="#projects" data-home-filter="illust">ILLUST</a>
    <p class="orbit-instruction">2025~2026</p>
    ${projects.map((p,i)=>{const group=p.category==='uxui'?uxPositions:illPositions,index=p.category==='uxui'?uxIndex++:illIndex++,raw=group[index%group.length],x=Math.max(12,Math.min(88,raw[0])),y=Math.max(12,Math.min(88,raw[1]));return `<a class="work-bubble project-bead ${p.category}" style="--x:${x}%;--y:${y}%;--i:${i}" href="#projects/${p.id}" aria-label="${p.name}"><span class="project-star" aria-hidden="true">*</span><span class="bubble-title">${p.name}</span></a>`}).join('')}
  </div>
</section>`}
function listing(){const list=projects.filter(p=>filter==='all'||p.category===filter),pageCount=Math.max(1,Math.ceil(list.length/9));projectPage=Math.min(projectPage,pageCount);const visible=list.slice((projectPage-1)*9,projectPage*9),emptySlots=Math.max(0,9-visible.length);return `<section class="archive"><div class="page-title"><h1>Projects<sup>${projects.length}</sup></h1><p>since 2025~</p></div><div class="filters" aria-label="프로젝트 분류">${[['all','All',projects.length],['uxui','UXUI',projects.filter(p=>p.category==='uxui').length],['illust','Illust',projects.filter(p=>p.category==='illust').length]].map(([id,t,n])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${t} <sup>${n}</sup></button>`).join('')}</div><div class="grid" aria-live="polite">${visible.map(card).join('')}${Array.from({length:emptySlots},()=>'<span class="card-placeholder" aria-hidden="true"></span>').join('')}</div><nav class="project-pagination" aria-label="프로젝트 페이지"><button data-project-page="${Math.max(1,projectPage-1)}" ${projectPage===1?'disabled':''} aria-label="이전 페이지">←</button>${Array.from({length:pageCount},(_,i)=>`<button data-project-page="${i+1}" aria-current="${projectPage===i+1?'page':'false'}">${String(i+1).padStart(2,'0')}</button>`).join('')}<button data-project-page="${Math.min(pageCount,projectPage+1)}" ${projectPage===pageCount?'disabled':''} aria-label="다음 페이지">→</button></nav></section>`}
function detail(p){
 const projectIndex=projects.indexOf(p),previous=projects[(projectIndex-1+projects.length)%projects.length],next=projects[(projectIndex+1)%projects.length];
 const toolIcons={figma:['Figma','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg'],photoshop:['Photoshop','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg'],illustrator:['Illustrator','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg'],'after-effects':['After Effects','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aftereffects/aftereffects-original.svg'],procreate:['Procreate','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/procreate/procreate-plain.svg'],premiere:['Premiere Pro','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/premierepro/premierepro-plain.svg'],blender:['Blender','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/blender/blender-original.svg'],notion:['Notion','https://cdn.jsdelivr.net/gh/devicons/devicon/icons/notion/notion-original.svg'],codex:['Codex','assets/codex.svg'],chatgpt:['ChatGPT','assets/chatgpt.webp'],claude:['Claude','assets/claude.svg'],gemini:['Gemini','assets/gemini.svg'],cursor:['Cursor','assets/cursor.svg']};
 const tools=Array.isArray(p.tools)&&p.tools.length?`<div class="project-tools" aria-label="사용한 툴">${p.tools.filter(id=>toolIcons[id]).map(id=>`<span title="${toolIcons[id][0]}"><img src="${toolIcons[id][1]}" alt="${toolIcons[id][0]}"></span>`).join('')}</div>`:'';
 const rows=(Array.isArray(p.contributions)?p.contributions:[{name:p.contribution||'',percent:p.contributionPercent||''}]).filter(row=>row&&String(row.name||'').trim());
 const contribution=rows.length?`<div class="contribution-list">${rows.map(row=>{const percent=Math.min(100,Math.max(0,Number(row.percent)||0));return `<div class="contribution-chart"><strong>${row.name}</strong><div class="contribution-track" role="img" aria-label="${row.name} 기여도 ${percent}퍼센트"><i style="--value:${percent}%"></i></div><span>${percent}%</span></div>`}).join('')}</div>`:'';
 const hasPrototype=p.category==='uxui'&&(p.figma||['onul','folio','morrow'].includes(p.id));
 const gallerySources=Array.isArray(p.gallery)&&p.gallery.length?p.gallery:[];
 const gallery=gallerySources.length?`<div class="project-gallery">${gallerySources.map((src,i)=>`<img src="${src}" alt="${p.name} 프로토타이핑 이미지 ${i+1}">`).join('')}</div>`:'';
 const prototype=hasPrototype?`<div class="project-prototype" aria-label="모바일 프로토타입">${p.figma?`<iframe class="figma-frame" title="${p.name} 인터랙티브 프로토타입" src="${PortfolioStore.figma(p.figma.replace(/&amp;/g,'&'))}" allowfullscreen></iframe>`:`<div class="prototype" id="prototype" aria-live="polite"></div>`}</div>`:'';
 const video=p.video?`<section class="project-video"><div class="section-head"><h2>VIDEO</h2><span class="tiny">YOUTUBE</span></div><div class="video-stage"><button data-video aria-label="YouTube 영상 재생">▶</button></div></section>`:'';
 const goal=String(p.question||'').trim(),description=String(p.desc||'').trim();
 const narrative=goal?`<div class="story"><h2>GOAL</h2><div><h3>${goal}</h3>${description?`<p>${lines(description)}</p>`:''}</div></div>`:(description?`<div class="story without-goal"><div><p>${lines(description)}</p></div></div>`:'');
 const inlineSources=Array.isArray(p.inlineGallery)&&p.inlineGallery.length?p.inlineGallery:[];
 const inlineGallery=inlineSources.length?`<div class="project-gallery project-gallery-inline">${inlineSources.map((src,i)=>`<img src="${src}" alt="${p.name} 본문 이미지 ${i+1}">`).join('')}</div>`:'';
 return `<div class="detail-top"><a href="#projects">← All projects</a><span>${p.category.toUpperCase()} / ${p.year}</span></div><section class="detail-title"><div><span class="eyebrow">${p.type}</span><h1>${p.name}</h1><h2>${p.tag}</h2></div><div>${tools}${contribution}<span class="tiny">${p.date||p.year}</span></div></section><section class="project-overview ${hasPrototype?'':'without-prototype'}"><div class="project-narrative">${narrative}${inlineGallery}</div>${prototype}${gallery}</section>${video}<div class="section-head project-navigation"><a href="#projects/${previous.id}">← ${previous.name}</a><a href="#projects/${next.id}">${next.name} →</a></div>`
}
function memoRow(m){return `<a class="memo-row" href="#memo/${m.id}"><small>${m.date}</small><div><h2>${m.title}</h2><p>${m.sub}</p></div><span class="tiny">${m.kind}</span><b>↗</b></a>`}
function memoPage(id){if(!id){let entries=[];try{entries=JSON.parse(localStorage.getItem('portfolio-guestbook')||'[]')}catch{}return `<section class="guestbook"><div class="page-title"><h1>Guestbook</h1><p>방문 감사합니다.<br>자유롭게 사용해주세요.</p></div><form class="guestbook-form"><div class="guestbook-credentials"><input name="guestName" placeholder="이름" maxlength="40" required><input name="guestPassword" type="password" placeholder="비밀번호 4자리" inputmode="numeric" pattern="[0-9]{4}" minlength="4" maxlength="4" required></div><textarea name="guestMessage" placeholder="방명록을 남겨주세요." maxlength="300" required></textarea><button class="black" type="submit">남기기</button></form><div class="guestbook-list">${entries.map((e,i)=>`<article><strong>${esc(e.name)}</strong><time>${esc(e.date)}</time><p>${esc(e.message)}</p><button class="guest-delete" data-guest-delete="${i}">삭제</button></article>`).join('')}</div></section>`}const m=memos.find(m=>m.id===id);return m?`<div class="detail-top"><a href="#memo">← Guestbook</a></div><article class="memo-body"><div class="eyebrow">${m.kind} / ${m.date}</div><h1>${m.title}</h1><p class="muted">${m.sub}</p>${m.body.map(p=>`<p>${p}</p>`).join('')}</article>`:notFound()}
function contact(){const instagram=String(profile.instagram||'').trim(),instagramHref=instagram?( /^https?:\/\//i.test(instagram)?instagram:`https://www.instagram.com/${instagram.replace(/^@/,'')}`):'';return `<section class="contact"><div class="page-title"><h1>Contact</h1></div><p>${lines(profile.contact)}</p><div class="contact-address"><div class="contact-email"><span class="email-label">email</span><a href="mailto:${profile.email}">${profile.email} ↗</a></div>${profile.phone?`<div class="contact-email"><span class="email-label">phone</span><a href="tel:${profile.phone}">${profile.phone} ↗</a></div>`:''}${instagram?`<div class="contact-email"><span class="email-label">instagram</span><a href="${instagramHref}" target="_blank" rel="noreferrer">${instagram} ↗</a></div>`:''}</div></section>`}
function notFound(){return '<section class="empty"><h1>페이지를 찾을 수 없습니다.</h1><a href="#projects">프로젝트로 돌아가기 ↗</a></section>'}
function renderProto(p){const el=document.querySelector('#prototype');if(!el)return;let body='';if(p.id==='onul'){body=proto.saved?`<div class="success-mark">✓</div><h3>오늘의 나를<br>남겼어요.</h3><p>기분: ${['평온해요','그저 그래요','지쳤어요','설레요'][proto.mood]}</p><p>${esc(proto.note)}</p><button class="primary" data-again>새 기록 남기기</button>`:`<small>ONUL — DAILY CHECK-IN</small><h3>오늘은,<br>어떤 하루인가요?</h3><p>지금의 마음에 가장 가까운 표정을 골라주세요.</p><div class="choices">${['☺','◡','☁','✳'].map((v,i)=>`<button data-mood="${i}" aria-label="${['평온해요','그저 그래요','지쳤어요','설레요'][i]}" aria-pressed="${proto.mood===i}">${v}</button>`).join('')}</div><label for="note">오늘의 한 줄</label><textarea id="note" placeholder="기억하고 싶은 순간을 남겨주세요." maxlength="150">${esc(proto.note||'')}</textarea><button class="primary" data-save>오늘 기록하기 ↗</button><p id="proto-message" role="status"></p>`;}else if(p.id==='folio'){let books=['작은 기쁨의 발견','느리게 읽는 마음','디자인의 시선'];let shown=proto.library?books.filter(b=>proto.books.includes(b)):books.filter(b=>b.includes(proto.query||''));body=`<small>FOLIO — YOUR READING SPACE</small><h3>읽고 싶은 마음을<br>한곳에.</h3><button class="pill" data-library>${proto.library?'책 둘러보기':'나의 서재'} (${proto.books.length})</button>${!proto.library?`<label for="search">책 검색</label><input id="search" placeholder="디자인, 마음, 기쁨" value="${esc(proto.query||'')}">`:''}<div>${shown.length?shown.map(b=>`<p>${b}</p><button class="secondary" data-book="${b}">${proto.books.includes(b)?'서재에서 삭제 −':'서재에 담기 +'}</button>`).join(''):'<p>아직 책이 없어요. 다른 검색어나 책을 찾아보세요.</p>'}</div>`;}else{const places={카페:['여백 커피','오후의 서재'],전시:['작은 형태전','일상의 장면'],산책:['숲길 한 바퀴','강변 노을길']};body=`<small>MORROW — NEARBY DISCOVERIES</small><h3>오늘의 발견은<br>어디에 있을까요?</h3><div class="choices">${Object.keys(places).map(k=>`<button style="font-size:12px" data-place-type="${k}" aria-pressed="${proto.kind===k}">${k}</button>`).join('')}</div>${places[proto.kind].map(n=>`<p>${n} <span class="muted">· 샘플 장소</span></p><button class="secondary" data-place="${n}">${proto.places.includes(n)?'방문 계획에서 빼기 −':'방문 계획에 담기 +'}</button>`).join('')}<p>나의 방문 계획 (${proto.places.length})</p><p>${proto.places.length?proto.places.join(' · '):'마음에 드는 장소를 골라주세요.'}</p>`;}el.innerHTML=`<div class="proto-status"><span>9:41</span><span>● ▰</span></div>${body}`;}
function resetProto(){proto={mood:null,note:'',saved:false,books:[],library:false,query:'',kind:'카페',places:[]}}
function route(){const parts=location.hash.replace(/^#\/?/,'').split('/'),page=parts[0]||'home';const p=projects.find(p=>p.id===parts[1]);resetProto();document.body.dataset.page=page;main.innerHTML=page==='home'?home():page==='projects'?(parts[1]?(p?detail(p):notFound()):listing()):page==='memo'?memoPage(parts[1]):page==='contact'?contact():notFound();document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(page==='home')initArchiveHome();if(p)renderProto(p);document.title=`${p?p.name:page.charAt(0).toUpperCase()+page.slice(1)} — KWON AHYEON`;window.scrollTo(0,0);if(matchMedia('(prefers-reduced-motion: reduce)').matches)stopAllMotion();}
function initArchiveHome(){const stage=document.querySelector('.work-orbit'),sound=document.querySelector('.sound-toggle'),frame=document.querySelector('#archive-audio'),canvas=document.querySelector('#lotus-canvas');let playing=false;const command=func=>frame?.contentWindow?.postMessage(JSON.stringify({event:'command',func,args:[]}),'*');if(sound)sound.addEventListener('click',()=>{playing=!playing;command(playing?'playVideo':'pauseVideo');if(playing)setTimeout(()=>command('playVideo'),300);sound.setAttribute('aria-pressed',String(playing));sound.setAttribute('aria-label',playing?'배경 음악 정지':'배경 음악 재생')});if(!stage||!canvas)return;const bubbles=[...stage.querySelectorAll('.work-bubble')],ctx=canvas.getContext('2d'),source=document.createElement('canvas'),sctx=source.getContext('2d'),img=new Image();let px=-9999,py=-9999,dots=[];img.src=window.LOTUS_IMAGE_DATA||'assets/lotus.jpg';img.onload=()=>{source.width=img.naturalWidth;source.height=img.naturalHeight;sctx.drawImage(img,0,0);const data=sctx.getImageData(0,0,source.width,source.height).data;for(let y=8;y<source.height;y+=11)for(let x=8;x<source.width;x+=11){const n=(y*source.width+x)*4,r=data[n],g=data[n+1],b=data[n+2];if(r+g+b<724&&r>g*1.03)dots.push({x:x/source.width,y:y/source.height,p:(x*13+y*7)%63})}};stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect();px=e.clientX-r.left;py=e.clientY-r.top});stage.addEventListener('pointerleave',()=>{px=-9999;py=-9999});const started=performance.now();function draw(now){if(!stage.isConnected)return;const rect=stage.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2),w=rect.width,h=rect.height;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);const size=Math.min(w*.84,h*.82),ox=(w-size)/2,oy=(h-size*.951)/2,t=(now-started)/1000;dots.forEach(d=>{const x=ox+d.x*size+Math.sin(t*.42+d.p)*1.25,y=oy+d.y*size*.951+Math.cos(t*.36+d.p)*1.8,near=Math.max(0,1-Math.hypot(px-x,py-y)/92);ctx.beginPath();ctx.arc(x,y,1.65+near*1.05,0,Math.PI*2);const heat=Math.pow(near,.72);ctx.fillStyle="rgb("+Math.round(170+56*heat)+" "+Math.round(170-20*heat)+" "+Math.round(170+17*heat)+")";ctx.fill()});bubbles.forEach((b,i)=>{const q=b.getBoundingClientRect(),distance=Math.hypot(px-(q.left-rect.left+q.width/2),py-(q.top-rect.top+q.height/2)),near=Math.max(0,1-distance/105),phase=i*1.37;b.style.setProperty('--float-x',(Math.sin(t*.44+phase)*2.7).toFixed(2)+'px');b.style.setProperty('--float-y',(Math.cos(t*.36+phase)*4).toFixed(2)+'px');b.style.setProperty('--proximity',near.toFixed(3));b.style.setProperty("--heat-color","rgb("+Math.round(170+56*Math.pow(near,.72))+" "+Math.round(170-20*Math.pow(near,.72))+" "+Math.round(170+17*Math.pow(near,.72))+")")});requestAnimationFrame(draw)}requestAnimationFrame(draw)}
function stopAllMotion(){document.querySelectorAll('img').forEach(img=>{if(img.getAttribute('src').startsWith('assets/')&&img.src.endsWith('.gif'))img.src=img.src.replace('.gif','.svg');else if(img.closest('.gif-stage'))img.hidden=true;});document.querySelectorAll('[data-motion]').forEach(b=>{b.textContent='움직임 재생';b.dataset.paused='true'})}
main.addEventListener('click',e=>{const link=e.target.closest('[data-home-filter]');if(!link)return;filter=link.dataset.homeFilter;projectPage=1});
main.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const p=projects.find(p=>location.hash==='#projects/'+p.id);if(b.dataset.filter){filter=b.dataset.filter;projectPage=1;main.innerHTML=listing();main.querySelector(`[data-filter="${filter}"]`).focus();if(matchMedia('(prefers-reduced-motion: reduce)').matches)stopAllMotion();return}if(b.dataset.projectPage){projectPage=Number(b.dataset.projectPage);main.innerHTML=listing();main.querySelector(`[data-project-page="${projectPage}"]`)?.focus();window.scrollTo({top:0,behavior:'smooth'});return}if(b.hasAttribute('data-video')){const id=p&&PortfolioStore.youtube(p.video);if(!id){b.parentElement.innerHTML='<span>유효한 YouTube 링크를 확인해 주세요.</span>';return}b.parentElement.innerHTML=`<iframe title="프로젝트 영상" src="https://www.youtube.com/embed/${id}?autoplay=1&rel=0" allow="autoplay; encrypted-media; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`;return}if(b.dataset.motion){const paused=b.dataset.paused!=='true';const img=b.parentElement.querySelector('img');if(p&&p.motion){img.hidden=paused;}else img.src=`assets/${b.dataset.motion}.${paused?'svg':'gif'}`;b.dataset.paused=String(paused);b.textContent=paused?'움직임 재생':'움직임 멈추기';return}if(b.hasAttribute('data-copy')){try{await navigator.clipboard.writeText(raw.profile.email);document.querySelector('#copy-status').textContent='이메일을 복사했습니다.'}catch{document.querySelector('#copy-status').textContent='복사가 지원되지 않습니다. 이메일 주소를 직접 복사해 주세요.'}return}if(!p)return;if(b.hasAttribute('data-reset')||b.hasAttribute('data-again'))resetProto();if(b.hasAttribute('data-mood')){proto.note=document.querySelector('#note').value;proto.mood=+b.dataset.mood}if(b.hasAttribute('data-save')){proto.note=document.querySelector('#note').value.trim();if(proto.mood===null||!proto.note){document.querySelector('#proto-message').textContent='기분을 고르고 한 줄을 입력해 주세요.';return}proto.saved=true}if(b.hasAttribute('data-library'))proto.library=!proto.library;if(b.dataset.book){proto.books=proto.books.includes(b.dataset.book)?proto.books.filter(v=>v!==b.dataset.book):[...proto.books,b.dataset.book]}if(b.dataset.placeType)proto.kind=b.dataset.placeType;if(b.dataset.place)proto.places=proto.places.includes(b.dataset.place)?proto.places.filter(v=>v!==b.dataset.place):[...proto.places,b.dataset.place];renderProto(p)});
main.addEventListener('submit',e=>{if(!e.target.matches('.guestbook-form'))return;e.preventDefault();const f=e.target,name=f.elements.guestName.value.trim(),message=f.elements.guestMessage.value.trim(),password=f.elements.guestPassword.value;if(!name||!message||!/^[0-9]{4}$/.test(password)){f.elements.guestPassword.focus();return}let entries=[];try{entries=JSON.parse(localStorage.getItem('portfolio-guestbook')||'[]')}catch{}entries.unshift({name,message,password,date:new Date().toLocaleDateString('ko-KR')});localStorage.setItem('portfolio-guestbook',JSON.stringify(entries.slice(0,100)));route()});
main.addEventListener('click',e=>{const b=e.target.closest('[data-guest-delete]');if(!b)return;let entries=[];try{entries=JSON.parse(localStorage.getItem('portfolio-guestbook')||'[]')}catch{}const i=Number(b.dataset.guestDelete);if(!window.portfolioAdminAuthenticated){const password=prompt('작성할 때 설정한 비밀번호를 입력하세요.');if(password===null)return;if(entries[i]?.password!==password){alert('비밀번호가 일치하지 않습니다.');return}}entries.splice(i,1);localStorage.setItem('portfolio-guestbook',JSON.stringify(entries));route()});
main.addEventListener('input',e=>{if(e.target.id==='note')proto.note=e.target.value;if(e.target.id==='search'){const start=e.target.selectionStart;proto.query=e.target.value;renderProto(projects.find(p=>p.id==='folio'));const input=document.querySelector('#search');input.focus();input.setSelectionRange(start,start)}});
document.querySelector('.wordmark').textContent=raw.profile.siteName||raw.profile.name;
document.querySelector('nav a[href="#memo"]').textContent='Guestbook';
document.querySelector('footer a').textContent=raw.profile.name+' © '+new Date().getFullYear();
document.querySelector('nav sup').textContent=projects.length;
window.addEventListener('message',e=>{const frame=document.querySelector('#archive-audio');if(!frame||e.source!==frame.contentWindow)return;try{const data=typeof e.data==='string'?JSON.parse(e.data):e.data,info=data?.info;if(typeof info?.duration==='number'&&info.duration>0)frame.dataset.duration=info.duration;if(typeof info?.currentTime==='number'){const duration=Number(frame.dataset.duration)||info.duration||0,progress=duration?Math.min(1,info.currentTime/duration):0;document.querySelector('.sound-toggle')?.style.setProperty('--progress',progress)}}catch{}});
setInterval(()=>{const frame=document.querySelector('#archive-audio');if(!frame)return;frame.contentWindow?.postMessage(JSON.stringify({event:'listening',id:'archive-audio'}),'*');['getCurrentTime','getDuration'].forEach(func=>frame.contentWindow?.postMessage(JSON.stringify({event:'command',func,args:[]}),'*'))},500);
new MutationObserver(()=>{const frame=main.querySelector('.figma-frame');if(!frame||frame.parentElement.classList.contains('figma-device-crop'))return;const crop=document.createElement('div');crop.className='figma-device-crop';frame.before(crop);crop.append(frame)}).observe(main,{childList:true,subtree:true});
window.addEventListener('hashchange',route);route();
})().catch(e=>{document.querySelector('main').textContent='콘텐츠를 불러오지 못했습니다. 관리자 화면에서 저장 데이터를 확인해 주세요.';console.error(e)});
