window.PortfolioStore=(()=>{
const clone=v=>JSON.parse(JSON.stringify(v));
function youtube(value){if(!value)return '';try{const u=new URL(value);if(u.protocol!=='https:')return '';const id=u.hostname==='youtu.be'?u.pathname.slice(1):['youtube.com','www.youtube.com','www.youtube-nocookie.com'].includes(u.hostname)?u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).at(-1):'';return /^[\w-]{11}$/.test(id||'')?id:''}catch{return ''}}
function figma(value){if(!value)return '';try{let source=value.trim();if(source.includes('&lt;')||source.includes('&quot;')||source.includes('&amp;')){const decoder=document.createElement('textarea');decoder.innerHTML=source;source=decoder.value.trim()}if(source.startsWith('<')){const doc=new DOMParser().parseFromString(source,'text/html'),frame=doc.body.firstElementChild;if(!frame||frame.tagName!=='IFRAME'||doc.body.children.length!==1)return '';source=frame.getAttribute('src')||''}const u=new URL(source);if(u.protocol!=='https:'||!['www.figma.com','figma.com','embed.figma.com'].includes(u.hostname))return '';if(!/^\/(proto|design|file|embed)\//.test(u.pathname)&&u.pathname!=='/embed')return '';if(u.hostname!=='embed.figma.com'&&u.pathname!=='/embed')u.hostname='embed.figma.com';u.searchParams.set('embed-host','share');u.searchParams.set('hide-ui','1');u.searchParams.set('show-proto-sidebar','false');u.searchParams.set('hotspot-hints','false');u.searchParams.set('device-frame','true');u.searchParams.set('scaling','contain');u.searchParams.set('content-scaling','fixed');u.searchParams.set('theme','light');u.searchParams.set('background-color','ffffff');return u.href}catch{return ''}}
function media(v){return !v||/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(v)||/^https:\/\/[^\s"<>]+$/.test(v)}
function validate(d){if(!d||d.version!==1||!d.profile||!Array.isArray(d.projects)||!Array.isArray(d.memos))throw Error('이 사이트에서 내보낸 백업 파일을 선택해 주세요.');const base=window.PORTFOLIO_DEFAULTS;const out={version:1,profile:{},projects:[],memos:[]};
const str=(o,k,max=20000)=>{if(typeof o[k]!=='string'||o[k].length>max)throw Error(k+' 항목의 형식이나 길이를 확인해 주세요.');return o[k]};
// 연락처 확장 필드는 기본 콘텐츠에 없던 이전 데이터에서도 항상 보존한다.
const contactValue=(profile,key)=>typeof profile[key]==='string'?profile[key]:'';
if(typeof d.profile.siteName!=='string')d.profile.siteName=d.profile.name||'프로필';Object.keys(base.profile).filter(k=>!['phone','instagram','contactImage'].includes(k)).forEach(k=>out.profile[k]=str(d.profile,k));out.profile.phone=contactValue(d.profile,'phone');out.profile.instagram=contactValue(d.profile,'instagram');out.profile.contactImage=contactValue(d.profile,'contactImage');if(!out.profile.name.trim()||!/^[^\s@<>"&]+@[^\s@<>"&]+\.[^\s@<>"&]+$/.test(out.profile.email))throw Error('이름과 올바른 이메일을 입력해 주세요.');
for(const kind of ['projects','memos']){if(d[kind].length>500)throw Error('항목은 최대 500개까지 저장할 수 있습니다.');const ids=new Set();out[kind]=d[kind].map(o=>{if(!o||!/^[-a-zA-Z0-9_]{1,100}$/.test(o.id)||ids.has(o.id))throw Error('항목 ID가 올바르지 않거나 중복됩니다.');ids.add(o.id);const r={id:o.id,published:o.published!==false};if(kind==='projects'){o.contribution=typeof o.contribution==='string'?o.contribution:'';o.contributionPercent=typeof o.contributionPercent==='string'?o.contributionPercent:''}const keys=kind==='projects'?['name','year','tag','type','contribution','contributionPercent','desc','question','solution']:['date','kind','title','sub'];keys.forEach(k=>r[k]=str(o,k));if(!(r.name||r.title||'').trim())throw Error('제목을 입력해 주세요.');if(kind==='projects'){if(!['uxui','illust'].includes(o.category))throw Error('프로젝트 분류를 확인해 주세요.');const rows=Array.isArray(o.contributions)?o.contributions:[{name:r.contribution,percent:r.contributionPercent}];if(rows.length>20)throw Error('기여 항목은 최대 20개까지 추가할 수 있습니다.');r.contributions=rows.map(row=>{if(!row||typeof row.name!=='string'||typeof row.percent!=='string'||row.name.length>200||!/^\d{0,3}$/.test(row.percent)||Number(row.percent||0)>100)throw Error('기여 분야와 기여도는 0부터 100 사이로 입력해 주세요.');return{name:row.name,percent:row.percent}});r.category=o.category;r.art=['phone','poster','orbital'].includes(o.art)?o.art:'orbital';r.gif=['orbit','lines'].includes(o.gif)?o.gif:'orbit';for(const k of ['thumbnail','cover','motion']){r[k]=o[k]||'';if(typeof r[k]!=='string'||r[k].length>12000000||!media(r[k]))throw Error('이미지는 PNG/JPG/WebP/GIF 파일 또는 HTTPS 주소를 사용해 주세요.')}r.video=o.video||'';r.figma=o.figma||'';if(r.video&&!youtube(r.video))throw Error('올바른 YouTube 영상 링크를 입력해 주세요.');if(r.figma&&!figma(r.figma))throw Error('올바른 Figma 임베드 코드 또는 공유 링크를 입력해 주세요.');}else{if(!Array.isArray(o.body)||o.body.some(v=>typeof v!=='string'||v.length>100000))throw Error('메모 본문 형식을 확인해 주세요.');r.body=o.body;}return r})}return out;}
async function read(){const source=clone(window.PORTFOLIO_DEFAULTS),valid=validate(source);valid.profile.phone=typeof source.profile.phone==="string"?source.profile.phone:"";valid.profile.instagram=typeof source.profile.instagram==="string"?source.profile.instagram:"";valid.profile.contactImage=typeof source.profile.contactImage==="string"?source.profile.contactImage:"";valid.projects.forEach((p,i)=>{p.date=typeof source.projects[i]?.date==="string"?source.projects[i].date:"";p.tools=Array.isArray(source.projects[i]?.tools)?source.projects[i].tools:[];p.gallery=Array.isArray(source.projects[i]?.gallery)?source.projects[i].gallery:[];p.inlineGallery=Array.isArray(source.projects[i]?.inlineGallery)?source.projects[i].inlineGallery:[]});return valid}
return {read,youtube,figma};
})();
